language: python
compiler:
  - python
before_install:
  - sudo apt-get update -qq
  - sudo apt-get dist-upgrade -qq
  - sudo apt-get install python-pip
  - sudo pip install ghp-import pelican cpp-coveralls --use-mirrors
script:
  - pelican -s pelican.conf.py . && ghp-import output && git push origin gh-pages
